// This file is generated by Prismic local builder. Update with care!

export { default as Text } from "./Text";

/**
 * A map of Slice types to Slice components.
 */
export const components = {
  text: Text,
};
